export const SUPERVISOR_CHECKLIST_ITEMS = [
  'Signboards',
  'Meter readings',
  'Parking',
  'Reception area',
  'Lounge area',
  'CCTV',
  'Sit out',
  'Walkway',
  'Washrooms and Dressing Room',
  'Rear parking area/nets area',
  'Drinking water availability',
  'Dugouts cleaning',
  "Pitch marking's",
  'Stumps',
  'Overall turf cleaning',
  'Turf light status',
  'Gallery lightings fans cleaning',
  'Cafe space & walkway',
  'Daily Bookings',
].map((label, index) => ({
  key: `supervisor-${String(index + 1).padStart(2, '0')}`,
  label,
  labelMl: '',
}));
