export const SUPERVISOR_CHECKLIST_ITEMS = [
  'Signboards',
  'Meter readings',
  'Parking',
  'Reception area',
  'Lounge area',
  'CCTV',
  'Sit out',
  'Walkway',
  'Washrooms and Dressing Room',
  'Rear parking area / Nets area',
  'Drinking water availability',
  'Dugouts cleaning',
  'Pitch markings',
  'Stumps',
  'Overall turf cleaning',
  'Turf light status (Full lighting is to be checked at least once in 3 days)',
  'Gallery lighting & fans cleaning',
  'Cafe space & walkway',
  'Daily bookings',
  'PlaySpot App',
  'Daily booking confirmation',
  'Players review',
  'Daily income and expenses',
  'Marketing management',
  'Safety equipment',
  'Inventory',
  'Ball availability',
  'Cash balance in office',
  'Diesel generator status',
].map((label, index) => ({
  key: `supervisor-${String(index + 1).padStart(2, '0')}`,
  label,
  labelMl: '',
}));
